:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\ExamPortal.API
dotnet build src\ExamPortal.API
echo Now, run the following to start the project: dotnet run -p src\ExamPortal.API\ExamPortal.API.csproj --launch-profile web.
echo.
