/*
 * Exam Portal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ExamPortal.API.Converters;

namespace ExamPortal.API.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AnswerUpdate : IEquatable<AnswerUpdate>
    {
        /// <summary>
        /// Gets or Sets QuestionId
        /// </summary>
        [Required]
        [DataMember(Name="questionId", EmitDefaultValue=true)]
        public int QuestionId { get; set; }

        /// <summary>
        /// Gets or Sets SelectedOptionId
        /// </summary>
        [DataMember(Name="selectedOptionId", EmitDefaultValue=true)]
        public int? SelectedOptionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AnswerUpdate {\n");
            sb.Append("  QuestionId: ").Append(QuestionId).Append("\n");
            sb.Append("  SelectedOptionId: ").Append(SelectedOptionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AnswerUpdate)obj);
        }

        /// <summary>
        /// Returns true if AnswerUpdate instances are equal
        /// </summary>
        /// <param name="other">Instance of AnswerUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnswerUpdate other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    QuestionId == other.QuestionId ||
                    
                    QuestionId.Equals(other.QuestionId)
                ) && 
                (
                    SelectedOptionId == other.SelectedOptionId ||
                    SelectedOptionId != null &&
                    SelectedOptionId.Equals(other.SelectedOptionId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + QuestionId.GetHashCode();
                    if (SelectedOptionId != null)
                    hashCode = hashCode * 59 + SelectedOptionId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AnswerUpdate left, AnswerUpdate right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AnswerUpdate left, AnswerUpdate right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
